### ISSUE TITLE
Iptrap2 on Amazon aws

### ISSUE THREAD

**Issue by kuindji** [jedisct1/iptrap#2]
Hi!

I am having trouble setting up iptrap2 on amazon ec2 instance. I am not sure if it is even possible (this is not my area of expertise). Is it possible?

After compiling and running the executable i am getting this error:

`./target/release/iptrap eth1 172.32.1.9 1000 1000`

> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ": SIOCETHTOOL(ETHTOOL_GET_TS_INFO) ioctl failed: No such device"', /checkout/src/libcore/result.rs:906:4

eth1 is a secondary network interface with public ip. I tried running iptrap with both eth1 not configured in /etc/network/interfaces and configured.

**Comment by cemasirt** [comment]
I have the same issue, I've run it with sudo, so I don't think it is a priviledge issue.
